name: Upload Action

on:
  workflow_dispatch:

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    # 移除了 environment 键
    env:
      API_TOKEN: ${{ secrets.API_KEY }}
      FILE_PATH: ./
      PROJECT_ID: ${{ secrets.PROJECT_ID }} # 已从 vars.ID 修改
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/MuXiu1997/ParaTranz-SDK-python.git
      - name: Upload To Paratranz
        run: |
          python .github/workflows/github2para.py